.TH "cparser/inc/cparser_config.h" 3 "Wed Sep 9 2020" "Version 1" "Cparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cparser/inc/cparser_config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCPARSER_CONFIG_MAX_NUM_OF_PARAMS\fP   5"
.br
.ti -1c
.RI "#define \fBCPARSER_CONFIG_MAX_NUM_OF_TRIGGERS\fP   25"
.br
.ti -1c
.RI "#define \fBCPARSER_CONFIG_MAX_TRIGGER_NAME_LENGTH\fP   10"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration parameters\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define CPARSER_CONFIG_MAX_NUM_OF_PARAMS   5"
Maximum number of parameters which a trigger can have\&. 
.SS "#define CPARSER_CONFIG_MAX_NUM_OF_TRIGGERS   25"
Maximum number of triggers which can be registered\&. 
.SS "#define CPARSER_CONFIG_MAX_TRIGGER_NAME_LENGTH   10"
Maximum trigger name length(except null terminator) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cparser from the source code\&.
