.TH "cparser/inc/generic.h" 3 "Wed Sep 9 2020" "Version 1" "Cparser" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cparser/inc/generic.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNULL\fP   ((void *)0U)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBBool_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB_Bool_t\fP { \fBFALSE\fP = 0, \fBTRUE\fP = !FALSE }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definitions which are used globally are contained in this file\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define NULL   ((void *)0U)"

.SH "Typedef Documentation"
.PP 
.SS "typedef uint8_t \fBBool_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fB_Bool_t\fP"
Boolean enumeration\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFALSE \fP\fP
FALSE 
.TP
\fB\fITRUE \fP\fP
TRUE 
.SH "Author"
.PP 
Generated automatically by Doxygen for Cparser from the source code\&.
